name = "nexmart-backend"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "nexmart-db"
database_id = "6e46edad-3cda-4c6e-a171-a07b90232f8b" # Production D1 ID
migrations_dir = "drizzle/migrations"

[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGIN = "*"
